import { action } from "./_generated/server";
import { v } from "convex/values";

function ensureRequiredKeys(output: Record<string, unknown>, requiredKeys: string[]) {
  for (const key of requiredKeys) {
    if (!(key in output)) {
      throw new Error(`LLM output missing required key: ${key}`);
    }
  }
}

function noMedicalViolation(text: string) {
  const blocked = ["diagnosi", "terapia", "prescrizione", "medical advice", "consult your doctor", "rischio clinico"];
  return blocked.filter((term) => text.toLowerCase().includes(term.toLowerCase()));
}

export const llmGateway = action({
  args: {
    agentName: v.string(),
    taskType: v.string(),
    input: v.any(),
    jsonSchema: v.object({
      requiredKeys: v.array(v.string())
    })
  },
  handler: async (_ctx, args) => {
    // MVP deterministic fallback; replace with provider call once API key/provider is wired.
    const output: Record<string, unknown> = {
      summary: `Generated by ${args.agentName} for ${args.taskType}`,
      items: Array.isArray((args.input as { items?: unknown[] }).items)
        ? (args.input as { items: unknown[] }).items
        : []
    };

    ensureRequiredKeys(output, args.jsonSchema.requiredKeys);

    const violationTerms = noMedicalViolation(JSON.stringify(output));
    if (violationTerms.length > 0) {
      throw new Error(`Compliance violation in llmGateway output: ${violationTerms.join(", ")}`);
    }

    return {
      output,
      usage: {
        promptTokens: 0,
        completionTokens: 0,
        estimatedCostUsd: 0
      }
    };
  }
});
